name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up PHP with GD extension
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: gd  # Install the GD extension

    - name: Change to server directory and copy .env
      working-directory: ./server
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Dependencies in server directory
      working-directory: ./server
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate key in server directory
      working-directory: ./server
      run: php artisan key:generate

    - name: Set directory permissions in server directory
      working-directory: ./server
      run: chmod -R 777 storage bootstrap/cache

    - name: Create SQLite database in server directory
      working-directory: ./server
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Run tests in server directory
      working-directory: ./server
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test
